# Generated by Django 4.0.1 on 2022-02-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'socical_companies',
            },
        ),
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('identification_number', models.CharField(max_length=500)),
                ('social_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_login', to='users.socialcompany')),
            ],
            options={
                'db_table': 'social_logins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('profile_image', models.URLField(max_length=500, null=True)),
                ('career', models.PositiveIntegerField(null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('is_subscription', models.BooleanField(default=False)),
                ('social_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.sociallogin')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
