# Generated by Django 4.0.2 on 2022-02-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitments', '0001_initial'),
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeapplication',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_applications', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='occupation_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='recruitments.occupationsubcategory'),
        ),
        migrations.AddField(
            model_name='occupationsubcategory',
            name='occupation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_subcategories', to='recruitments.occupationcategory'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='users.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitments.applicationstatus'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.sociallogin'),
        ),
    ]
