# Generated by Django 4.0.2 on 2022-02-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='occupation_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='recruitments.occupationsubcategory'),
        ),
    ]
