# Generated by Django 4.0.1 on 2022-02-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_name'),
        ('recruitments', '0003_alter_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ManyToManyField(through='recruitments.ResumeApplication', to='resumes.Resume'),
        ),
    ]
